kind: pipeline
type: docker

steps:
- name: test
  image: maven:3-jdk-11
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
  when:
    event:
      include:     
      - pull_request

- name: Sonarqube-analisis 
  image: maven:3-jdk-11
  commands:
    - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=Jmo=47558520 -Dsonar.host.url=http://104.43.137.120:9000
  when:
    event:
      include:     
      - pull_request

- name: SonarQualityGate
  image: maven:3-jdk-11
  commands:
  - mvn clean verify sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=Jmo=47558520 -Dsonar.host.url=http://104.43.137.120:9000
  when:
    event:
      include:     
      - pull_request

- name: CorreoPipelineStatusSonar
  image: drillster/drone-email
  settings:
    from: cakedaybakerywelcome@gmail.com
    host: smtp.gmail.com
    port: 465
    username:
      from_secret: correo
    password: 
      from_secret: correoPassword    
    recipients:
        - jorge.marroquin.ochoa@gmail.com
        - marroquin181358@unis.edu.gt
    subject: Pipeline DRONE Status
    body: La pipeline ha finalizado
  when:
    event:
      include:     
      - pull_request
    status:      
    - failure 

- name: tomcatDEV
  image: maven:3-jdk-11
  commands:
    - mvn -Dspring.profiles.active=dev clean  install
    - mvn -Dspring.profiles.active=dev package
    - cd target/
    - mv  ventas-0.0.1-SNAPSHOT.war devDrone.war
    - curl -v -u admin:adminSecure -T devDrone.war 'http://104.43.137.120:8085/manager/text/deploy?path=/devDrone&update=true'
  when:
    branch:
      - dev
    event:
      include:
      - push

- name: tomcatUAT
  image: maven:3-jdk-11
  commands:
    - mvn -Dspring.profiles.active=uat clean  install
    - mvn -Dspring.profiles.active=uat package
    - cd target/
    - mv  ventas-0.0.1-SNAPSHOT.war uatDrone.war
    - curl -v -u admin:adminSecure -T uatDrone.war 'http://104.43.137.120:8085/manager/text/deploy?path=/uatDrone&update=true'
  when:
    branch:
      - uat
    event:
      include:
      - push

- name: tomcatMAIN
  image: maven:3-jdk-11
  commands:
    - mvn -Dspring.profiles.active=main clean  install
    - mvn -Dspring.profiles.active=main package
    - cd target/
    - mv  ventas-0.0.1-SNAPSHOT.war mainDrone.war
    - curl -v -u admin:adminSecure -T mainDrone.war 'http://104.43.137.120:8085/manager/text/deploy?path=/mainDrone&update=true'
  when:
    branch:
      - main
    event:
      include:
      - push



- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slackWebhook
    channel: drone
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded in branch ${DRONE_BRANCH}. Good job.
      {{else}}
        build {{build.number}} failed in branch ${DRONE_BRANCH}. Fix me please.
      {{/success}}
  when:
    status:      
    - failure 
    - success

- name: CorreoPipelineStatus
  image: drillster/drone-email
  settings:
    from: cakedaybakerywelcome@gmail.com
    host: smtp.gmail.com
    port: 465
    username:
      from_secret: correo
    password: 
      from_secret: correoPassword    
    recipients:
        - jorge.marroquin.ochoa@gmail.com
        - marroquin181358@unis.edu.gt
    subject: Pipeline DRONE {{build.status}} ${DRONE_BRANCH}
    body: >
      {{#success build.status}}
        Build {{build.number}} finalizada con el status {{build.status}} en la rama ${DRONE_BRANCH} puedes ver los resultados en {{build.link}}
      {{else}}${DRONE_STEP_NAME}
        Build {{build.number}} finalizada con el status {{build.status}} en la rama ${DRONE_BRANCH} puedes ver los errores en {{build.link}}
      {{/success}}
  + attachment: build-result.xml
  when:
    status:      
    - failure 
    - success