kind: pipeline
type: docker
name: default


steps:
- name: test
  image: maven:3-jdk-11
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

- name: sonar
  image: maven:3-jdk-11
  commands:
    - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=Jmo=47558520 -Dsonar.host.url=http://104.43.137.120:9000/ -Dsonar.projectName=VentasDrone
+ level: DEBUG