kind: pipeline
name: default

steps:
- name: test
  image: maven:3-jdk-11
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
  when:
    event:
      include:     
      - pull_request

- name: SonarQualityGate
  image: maven:3-jdk-11
  commands:
  - mvn sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=${sonarPassword} -Dsonar.host.url=http://104.43.137.120:9000
  when:
    event:
      include:     
      - pull_request

- name: CorreoSonar
  image: drillster/drone-email
  settings:
    from: Pipeline Drone Failed
    host: smtp.sendgrid.net
    port: 465
    username:
      from_secret: correo
    password: 
      from_secret: correoPassword    
    recipients:
        - marroquin181358@unis.edu.gt
    body: El código no ha pasado la quality gate de sonarqube
    attachment: build-result.xml
  when:
    event:
      include:     
      - pull_request
    status:      
    - failure

- name: tomcatDEV
  image: maven:3-jdk-11
  commands:
    - mvn -Dspring.profiles.active=uat clean  install
    - mvn -Dspring.profiles.active=uat package
    - cd target/
    - mv  ventas-0.0.1-SNAPSHOT.war devDrone.war
    - curl -v -u admin:admin -T devDrone.war 'http://104.43.137.120:8085/manager/text/deploy?path=/devDrone&update=true'
  when:
    branch:
      - dev

- name: tomcatUAT
  image: alpine
  commands:
    - cd target/
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war uatDrone.war
    - curl -v -u admin:${tomcatPassword} -T uatDrone.war 'http://104.43.137.120:8085/manager/text/deploy?path=/uatDrone&update=true'
  when:
    branch:
      - uat

- name: tomcatMAIN
  image: alpine
  commands:
    - cd target/
    - apk add curl
    - stat ventas-0.0.1-SNAPSHOT.war
    - mv  ventas-0.0.1-SNAPSHOT.war mainDrone.war
    - curl -v -u admin:admin -T mainDrone.war 'http://104.43.137.120:8085/manager/text/deploy?path=/mainDrone&update=true'
  when:
    branch:
      - main